### ISSUE TITLE
can not reach the performance as the paper says

### ISSUE THREAD

**Issue by CharlesIsMeee** [alanqrwang/HQSNet#4]

**Comment by alanqrwang** [comment]
Hello, can you provide some details on your training setup? What data are you using, the image resolution, the forward model, etc.?

**Comment by CharlesIsMeee** [comment]
> Hello, can you provide some details on your training setup? What data are you using, the image resolution, the forward model, etc.?

My datasets are from HCP. Each image size is 145*174. I trained this model on high b value DWIs and all train step is same as the original code

**Comment by CharlesIsMeee** [comment]
I tried several unsupervised model on this dataset，and all this model got a acceptable results, so I think the dataset is not the reason. Maybe the reason is this dataset is unsuitable with this model

**Comment by alanqrwang** [comment]
There are a couple of important hyperparameters for this model which may heavily influence the performance. The most important are `--tv_coeff` and `--w_coeff`, which will weight the two regularization functions. Are you using the default values? If you could visualize and share some reconstructions, that would give me a better idea of which values (lower or higher) to try.

In general, if the reconstructions are overly smooth (e.g. overly blocky or even completely white or black), then the weight on `--tv_coeff` might be too high. If the reconstructions have many sprinkle artifacts, then weight on `--w_coeff` might be too high. Here is a visualization, where alpha is the weight on `--w_coeff` and beta is the weight on `--tv_coeff`. 
<img width="414" alt="slices" src="https://user-images.githubusercontent.com/60155768/164238945-06feabda-8cc2-44e6-b566-509ecc325e67.PNG">

**Comment by CharlesIsMeee** [comment]
Thanks very much ! !
